# lightning.pytorch==2.0.1.post0
seed_everything: 42
trainer:
  accelerator: cpu
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: resnet18-vanilla
      save_dir: .
      version: null
      offline: false
      dir: null
      id: null
      anonymous: null
      project: image-classification-KD
      log_model: True
      experiment: null
      prefix: ''
      checkpoint_name: null
      job_type: Train
      config: null
      entity: null
      reinit: null
      tags: null
      group: null
      notes: null
      magic: null
      config_exclude_keys: null
      config_include_keys: null
      mode: null
      allow_val_change: null
      resume: null
      force: null
      tensorboard: null
      sync_tensorboard: null
      monitor_gym: null
      save_code: null
      settings: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 2
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: 0.25
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 5
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: true
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: true
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
data:
  data_dir: ./datasets
  batch_size: 128
  num_workers: 4
  split_size: 0.8
  seed: 42
  test_transform: null
  train_transform: null
model:
  class_path: src.training.LightningTraining
  init_args:
    model: null
    model_name: resnet18
    num_classes: 37
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.001
    nesterov: true
    T_max: 10
